#!/usr/bin/env python3
"""Import non-PDF sources into the canonical block format the profiler reads.

Why this module exists
----------------------
paper-metrics measures MinerU content_list.json, and until now only paper-reader
could produce that file - a GPU conversion at ~6 minutes per paper whose bytes
move with engine versions.  Two consequences made the metrics layer untestable in
the honest sense:

1. A regression fixture that can only be regenerated by re-running a GPU
   conversion is not a fixture; it is a machine-local artefact.  The registered
   corpora (vrp-en, ycgl-zh) live on an external drive and the audit that pins
   them cannot run anywhere else.
2. The documents that matter most for validating the metrics layer - a rejected
   manuscript, a revision round, a response to reviewers - are never published
   PDFs at all.  They are .docx/.md files the author still owns and they have no
   paper-reader path.

The importer writes the *exact* layout discover_papers_detailed() walks, so the
profiler, the audit, the contract builder and the draft validator are unchanged.
Provenance is recorded as an import, never faked as a conversion: engines is
"import", both engine ok-flags are false, every engine version is null.

Determinism is a hard requirement, not a nicety: re-importing the same source must
produce byte-identical output, because the corpus id (and therefore every pinned
expected value downstream) is a hash of these files.  No timestamps anywhere in
the output; identity comes from the source sha256.

Heading levels follow the MinerU convention the profiler assumes: '#' is the
document title (text_level 1) and '##' starts a section (text_level 2).  Only
level-2 headings delimit sections in Paper.labelled_blocks(), so a manuscript that
uses '#' for every section has no sections at all - its whole body is front_matter
and canonical_text() is empty.  That is the one way to get an all-null profile from
a non-empty document, so section headings must be '##'.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
from pathlib import Path
from typing import Final

# The JSON boundary type lives in doc_model; re-exporting it here keeps a single
# definition instead of a second drifting copy.
from doc_model import JsonValue

#: Bumped when the emitted block shape changes; recorded in _META.json so a stale
#: fixture is detectable instead of silently re-interpreted.
IMPORTER_VERSION: Final = "1.0"

#: Built from chr(96) so this source file carries no backtick characters.
_FENCE: Final = chr(96) * 3


class CanonicalImportError(Exception):
    """A source document could not be converted into canonical blocks."""

    def __init__(self, path: Path, reason: str) -> None:
        super().__init__(f"{path}: {reason}")
        self.path: Path = path
        self.reason: str = reason


# ---------------------------------------------------------------------------
# Markdown parsing
# ---------------------------------------------------------------------------

_ATX_RE: Final = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
_FENCE_RE: Final = re.compile(r"^" + _FENCE + r"(.*)$")
_DISPLAY_RE: Final = re.compile(r"^\$\$")
_TABLE_SEP_RE: Final = re.compile(r"^\|[\s:|-]+\|$")
_LIST_RE: Final = re.compile(r"^(?:[-*+]\s+|\d+[.)]\s+)(.+)$")
_IMAGE_RE: Final = re.compile(r"^!\[([^\]]*)\]\(([^)]+)\)\s*$")
_MERGE_H_RE: Final = re.compile(r"<<(\d+)\s*$")
_MERGE_V_RE: Final = re.compile(r"\^\^(\d+)\s*$")
#: A standalone paragraph that is really a float caption waiting for its asset.
_CAPTION_RE: Final = re.compile(r"^(?:表|Table|图|Fig(?:ure)?)\s*\d+", re.IGNORECASE)


def _is_fence(line: str) -> bool:
    return bool(_FENCE_RE.match(line.strip()))


def _is_table_start(lines: list[str], index: int) -> bool:
    """A pipe row is a table only when the next line is the delimiter row."""
    if not lines[index].strip().startswith("|"):
        return False
    if index + 1 >= len(lines):
        return False
    return bool(_TABLE_SEP_RE.match(lines[index + 1].strip()))


def _split_row(line: str) -> list[str]:
    """Markdown pipe row -> cell texts, honouring escaped pipes."""
    body = line.strip()
    body = body.removeprefix("|")
    body = body.removesuffix("|")
    cells: list[str] = []
    buf: list[str] = []
    escape = False
    for char in body:
        if escape:
            buf.append(char)
            escape = False
        elif char == "\\":
            escape = True
        elif char == "|":
            cells.append("".join(buf))
            buf = []
        else:
            buf.append(char)
    cells.append("".join(buf))
    return [cell.strip() for cell in cells]


def _merge_parse_cell(raw: str) -> tuple[str, int, int]:
    """Split a friendly-merge cell into (text, colspan, rowspan).

    Mirrors thesis-writing/scripts/check_markdown_spec.py::_merge_parse_cell, the
    single definition of this syntax in the repo: the marker is anchored at the
    END of the cell so 'data<<2 more' is prose, not a merge.  A bare '^^' is a
    continuation placeholder (rowspan 0) meaning "the cell above keeps going".
    """
    text = raw.strip()
    col = 1
    match_h = _MERGE_H_RE.search(text)
    if match_h:
        col = int(match_h.group(1))
        text = text[:match_h.start()].strip()
    if text == "^^":
        return ("", 1, 0)
    row = 1
    match_v = _MERGE_V_RE.search(text)
    if match_v:
        row = int(match_v.group(1))
        text = text[:match_v.start()].strip()
    return text, col, row


def _grid_to_html(rows: list[list[str]]) -> str:
    """Render markdown rows (with friendly merge markers) as an HTML table.

    The HTML is what doc_model.html_to_text() strips, so cell text survives
    verbatim and the merge markers become real colspan/rowspan attributes - the
    same attributes S-TBL-06 sums as the declared column count.  A merge must not
    also emit the cells it covers, otherwise a 3-column merge would read as a row
    full of empty cells and poison S-TBL-07 (empty-cell share).

    Width comes from the header row, matching the checker's own notion of the
    table's declared column count; cells past that width are padding and dropped.
    """
    if not rows:
        return ""
    parsed = [[_merge_parse_cell(cell) for cell in row] for row in rows]
    width = sum(col for _, col, _ in parsed[0])
    if width == 0:
        return ""
    # Each entry is (row, column, colspan, rowspan, text) and owns the grid area
    # it spans, so a later bare ^^ can find and extend it.
    cells: list[list] = []
    covered: set[tuple[int, int]] = set()

    def _owner_at(row: int, column: int) -> int | None:
        for idx, (r0, c0, col, row_span, _text) in enumerate(cells):
            if r0 <= row < r0 + row_span and c0 <= column < c0 + col:
                return idx
        return None

    for r, row in enumerate(parsed):
        column = 0
        for text, col, row_span in row:
            while column < width and (r, column) in covered:
                column += 1
            if column >= width:
                break  # padding beyond the declared width
            if row_span == 0:
                # bare ^^: the cell above this column continues into this row
                owner = _owner_at(r - 1, column)
                if owner is not None:
                    cells[owner][3] += 1
                    covered.add((r, column))
                column += 1
                continue
            cells.append([r, column, col, row_span, text])
            last = len(cells) - 1
            for rr in range(r, min(r + row_span, len(parsed))):
                for cc in range(column, min(column + col, width)):
                    covered.add((rr, cc))
            column += col

    by_row: list[list[str]] = [[] for _ in parsed]
    for r, c0, col, row_span, text in cells:
        attrs = ""
        if col > 1:
            attrs += ' colspan="%d"' % col
        if row_span > 1:
            attrs += ' rowspan="%d"' % row_span
        by_row[r].append("<td" + attrs + ">" + html.escape(text) + "</td>")
    html_rows = ["".join(row) for row in by_row if row]
    if not html_rows:
        return ""
    return "<table>" + "".join("<tr>" + part + "</tr>" for part in html_rows) + "</table>"


def _strip_yaml_front_matter(text: str) -> tuple[str, str | None]:
    """Return (body, front_matter) when the document opens with a YAML block."""
    if not text.startswith("---"):
        return text, None
    end = text.find("\n---", 3)
    if end == -1:
        return text, None
    front = text[3:end].strip()
    return text[end + 4:], front or None


def _flush_caption(blocks: list[dict[str, JsonValue]],
                   pending: str | None) -> None:
    """A caption that never found its asset is still prose and must not vanish."""
    if pending is not None:
        blocks.append({"type": "text", "text": pending})


def markdown_to_blocks(text: str, *, slim: bool = False) -> list[dict[str, JsonValue]]:
    """Convert Markdown to canonical blocks.

    slim drops image blocks entirely (S-SIZ-04 then reads nothing on this
    document) - the fixture mode, because figure bytes are what makes a committed
    fixture heavy.
    """
    body, front = _strip_yaml_front_matter(text)
    lines = body.split("\n")
    blocks: list[dict[str, JsonValue]] = []
    if front is not None:
        # Kept as prose, not parsed: canonical_text() classifies the pre-heading
        # region as front_matter on its own, and a human reading the canonical
        # text should still see title and authors.
        for line in front.splitlines():
            line = line.strip()
            if line:
                blocks.append({"type": "text", "text": line})
    pending_caption: str | None = None
    index = 0
    count = len(lines)
    while index < count:
        line = lines[index].strip()

        if not line:
            index += 1
            continue

        # Fenced code block: the fence is the only boundary; the language tag is
        # kept out of the code text so it is not measured as prose.
        if _is_fence(line):
            index += 1
            body_lines: list[str] = []
            while index < count and not _is_fence(lines[index]):
                body_lines.append(lines[index])
                index += 1
            if index < count:
                index += 1  # consume the closing fence
            blocks.append({"type": "code", "text": "\n".join(body_lines)})
            continue

        atx = _ATX_RE.match(line)
        if atx:
            _flush_caption(blocks, pending_caption)
            pending_caption = None
            blocks.append({"type": "text", "text": atx.group(2).strip(),
                           "text_level": min(len(atx.group(1)), 3)})
            index += 1
            continue

        # Display math: the delimiter may open and close on the same line.
        if _DISPLAY_RE.match(line):
            rest = line[2:]
            if rest.endswith("$$"):
                inner = rest[:-2]
                index += 1
            else:
                inner = rest
                index += 1
                while index < count and not lines[index].strip().endswith("$$"):
                    inner += "\n" + lines[index].strip()
                    index += 1
                if index < count:
                    inner += "\n" + lines[index].strip()[:-2]
                    index += 1
            blocks.append({"type": "equation", "text": inner.strip()})
            continue

        if _is_table_start(lines, index):
            rows = [_split_row(lines[index])]
            index += 2
            while index < count and lines[index].strip().startswith("|"):
                rows.append(_split_row(lines[index]))
                index += 1
            block: dict[str, JsonValue] = {
                "type": "table", "table_body": _grid_to_html(rows)}
            if pending_caption is not None:
                block["table_caption"] = [pending_caption]
                pending_caption = None
            blocks.append(block)
            continue

        image = _IMAGE_RE.match(line)
        if image:
            caption = image.group(1).strip()
            if slim:
                _flush_caption(blocks, pending_caption)
                pending_caption = None
                index += 1
                continue
            block = {"type": "image", "img_path": image.group(2).strip()}
            if caption:
                block["img_caption"] = [caption]
            elif pending_caption is not None:
                block["img_caption"] = [pending_caption]
                pending_caption = None
            blocks.append(block)
            index += 1
            continue

        if _LIST_RE.match(line):
            items: list[str] = []
            while index < count:
                item = _LIST_RE.match(lines[index].strip())
                if item is None:
                    break
                items.append(item.group(1).strip())
                index += 1
            _flush_caption(blocks, pending_caption)
            pending_caption = None
            blocks.append({"type": "list", "list_items": items})
            continue

        # Paragraph: runs to the next blank line or block-starting construct.
        para_lines: list[str] = []
        while index < count:
            candidate = lines[index].strip()
            if (not candidate or _is_fence(candidate) or _ATX_RE.match(candidate)
                    or _DISPLAY_RE.match(candidate)
                    or _IMAGE_RE.match(candidate) or _LIST_RE.match(candidate)
                    or _is_table_start(lines, index)):
                break
            para_lines.append(candidate)
            index += 1
        paragraph = " ".join(para_lines).strip()
        if not paragraph:
            continue
        if _CAPTION_RE.match(paragraph):
            pending_caption = paragraph
            continue
        _flush_caption(blocks, pending_caption)
        pending_caption = None
        blocks.append({"type": "text", "text": paragraph})

    _flush_caption(blocks, pending_caption)
    return blocks


# ---------------------------------------------------------------------------
# docx parsing
# ---------------------------------------------------------------------------

#: A numbered Chinese section heading in a docx that does not use real Heading
#: styles: "1 引言", "3.1 柱体编码器", "4实验与结果".  Required because real
#: revision manuscripts (the 返修稿 this importer exists to serve) are exported
#: from Chinese templates whose headings sit in Normal.  Deliberately strict so
#: it cannot swallow prose: no terminator, no digit after the title, <= 24 chars.
_ZH_NUMBERED_HEADING = re.compile(r"^(\d{1,2}(?:\.\d{1,2}){0,3})\s*"
                                 r"([^\d].{0,23})$")
#: Characters that, if present, prove a line is a sentence and not a heading.
_SENTENCE_TERMINATORS = "。！？!?…;；"


def _docx_heading_level(text: str) -> int | None:
    """Level 1-4 for a numbered Chinese heading, else None.

    Only fires when the line carries no sentence terminator and the title part
    is short - a real prose sentence starting with a number ("3 个仓库被使用。")
    fails both checks and stays body text.
    """
    if any(ch in text for ch in _SENTENCE_TERMINATORS):
        return None
    match = _ZH_NUMBERED_HEADING.match(text)
    if match is None:
        return None
    numbering = match.group(1)
    title = match.group(2).strip()
    if not title:
        return None
    # "1.2.3.4 实验" is 4 levels deep; clamp to the 3 the profiler uses
    return min(len(numbering.split(".")), 3)


def docx_to_blocks(path: Path, *, slim: bool = False) -> list[dict[str, JsonValue]]:
    """Convert a .docx to canonical blocks (python-docx, already a dependency).

    Headings map to text_level; body paragraphs to text; tables to the same HTML
    the markdown path emits.  Equations and lists have no distinct docx block type
    here and remain paragraphs - measured as prose, the conservative choice for a
    metrics input.
    """
    try:
        import docx as python_docx
    except ImportError as exc:  # pragma: no cover - dependency is declared
        raise CanonicalImportError(path, f"python-docx unavailable: {exc}") from exc
    try:
        document = python_docx.Document(str(path))
    except Exception as exc:
        raise CanonicalImportError(path, f"unreadable docx: {exc}") from exc

    blocks: list[dict[str, JsonValue]] = []
    for paragraph in document.paragraphs:
        text = paragraph.text.strip()
        if not text:
            continue
        style = (paragraph.style.name or "") if paragraph.style is not None else ""
        heading = re.fullmatch(r"Heading (\d)", style)
        if heading:
            blocks.append({"type": "text", "text": text,
                           "text_level": min(int(heading.group(1)), 3)})
        else:
            # A Chinese template heading in Normal style: numbered, short,
            # terminator-free.  Detected, never guessed from the style table.
            zh_level = _docx_heading_level(text)
            if zh_level is not None:
                blocks.append({"type": "text", "text": text,
                               "text_level": zh_level})
            else:
                blocks.append({"type": "text", "text": text})
    for table in document.tables:
        rows: list[list[str]] = []
        for row in table.rows:
            seen: set[int] = set()
            cells: list[str] = []
            for cell in row.cells:
                tc_id = id(cell._tc)
                if tc_id in seen:
                    continue
                seen.add(tc_id)
                cells.append(cell.text.strip())
            rows.append(cells)
        table_html = _grid_to_html(rows)
        if table_html:
            blocks.append({"type": "table", "table_body": table_html})
    if slim:
        blocks = [b for b in blocks if b.get("type") not in ("image", "chart")]
    return blocks


def plain_text_to_blocks(text: str) -> list[dict[str, JsonValue]]:
    """A plain-text fallback: one text block per blank-line-separated group.

    There is no heading information, so the whole document is front_matter until
    the profiler's own classifier decides otherwise - honest for a .txt source,
    which genuinely carries no structure.
    """
    blocks: list[dict[str, JsonValue]] = []
    for paragraph in re.split(r"\n\s*\n", text):
        paragraph = paragraph.strip()
        if paragraph:
            blocks.append({"type": "text", "text": paragraph})
    return blocks


# ---------------------------------------------------------------------------
# Provenance / writing
# ---------------------------------------------------------------------------

def sha256_bytes(data: bytes) -> str:
    digest = hashlib.sha256()
    digest.update(data)
    return digest.hexdigest()


def _source_text(blocks: list[dict[str, JsonValue]]) -> str:
    """Every field doc_model treats as prose-ish text, joined for language stats."""
    parts: list[str] = []
    for block in blocks:
        for key in ("text", "table_body"):
            value = block.get(key)
            if isinstance(value, str):
                parts.append(value)
        items = block.get("list_items")
        if isinstance(items, list):
            parts.extend(str(item) for item in items if isinstance(item, str))
        for key, value in block.items():
            if key.endswith("_caption") and isinstance(value, list):
                parts.extend(str(item) for item in value if isinstance(item, str))
    return "\n".join(parts)


def build_meta(*, blocks: list[dict[str, JsonValue]], source_name: str,
               source_sha256: str, source_format: str) -> dict[str, JsonValue]:
    """_META.json for an imported document.

    Mirrors paper-reader key set so downstream consumers need no second schema,
    and fills every engine field with null - no engine ran.  Language uses
    text_metrics.detect_language, the identical rule paper-reader and the metrics
    layer share, so the cross-layer check stays meaningful.
    """
    import text_metrics

    language = text_metrics.detect_language(_source_text(blocks))
    return {
        "engines": "import",
        "marker": {"ok": False},
        "mineru": {"ok": False},
        "pdf_sha256": None,
        "pdf_sha256_note": "imported from " + source_format + "; source is not a PDF",
        "engine_versions": {
            "marker": None, "mineru": None, "surya": None,
            "torch": None, "cuda": None, "python": None,
        },
        "engine_versions_source": "not_applicable",
        "engine_versions_note": "no conversion engine ran; source was imported",
        "language": language["language"],
        "cjk_ratio": language["cjk_ratio"],
        "lang_source": "import_source_text",
        "import_provenance": {
            "importer_version": IMPORTER_VERSION,
            "source_format": source_format,
            "source_name": source_name,
            "source_sha256": source_sha256,
        },
    }


def write_paper(*, out_dir: Path, paper_id: str, blocks: list[dict[str, JsonValue]],
                meta: dict[str, JsonValue]) -> Path:
    """Write one canonical paper directory in paper-reader's layout.

    Sorting the JSON keys makes the output byte-stable across Python versions;
    block order is document order and must not be sorted.
    """
    paper_dir = out_dir / paper_id
    content_dir = paper_dir / "mineru" / paper_id / "auto"
    content_dir.mkdir(parents=True, exist_ok=True)
    content_path = content_dir / (paper_id + "_content_list.json")
    payload = json.dumps(blocks, ensure_ascii=False, indent=2, sort_keys=True)
    content_path.write_text(payload + "\n", encoding="utf-8")
    meta_path = paper_dir / "_META.json"
    meta_path.write_text(
        json.dumps(meta, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8")
    return paper_dir


def _load_blocks(path: Path, source_format: str,
                 slim: bool) -> list[dict[str, JsonValue]]:
    if source_format == "markdown":
        return markdown_to_blocks(path.read_text(encoding="utf-8"), slim=slim)
    if source_format == "docx":
        return docx_to_blocks(path, slim=slim)
    if source_format == "text":
        return plain_text_to_blocks(path.read_text(encoding="utf-8"))
    raise CanonicalImportError(path, "unsupported format " + repr(source_format))


_EXTENSIONS: Final = {".md": "markdown", ".markdown": "markdown",
                      ".txt": "text", ".docx": "docx"}


def import_file(source: Path, out_dir: Path, *, paper_id: str | None = None,
                source_format: str | None = None, slim: bool = False) -> Path:
    """Import one source file into a canonical paper directory."""
    if not source.is_file():
        raise CanonicalImportError(source, "source file not found")
    if source_format is None:
        source_format = _EXTENSIONS.get(source.suffix.lower(), "")
        if not source_format:
            raise CanonicalImportError(
                source, "unknown extension " + repr(source.suffix) + "; pass --format")
    paper_id = paper_id or source.stem
    blocks = _load_blocks(source, source_format, slim)
    if not blocks:
        raise CanonicalImportError(source, "no blocks produced; source is empty")
    meta = build_meta(blocks=blocks, source_name=source.name,
                      source_sha256=sha256_bytes(source.read_bytes()),
                      source_format=source_format)
    return write_paper(out_dir=out_dir, paper_id=paper_id, blocks=blocks, meta=meta)


def import_corpus(source_dir: Path, out_dir: Path,
                  *, slim: bool = False) -> list[Path]:
    """Import every recognised file in a directory as one paper each."""
    imported: list[Path] = []
    for path in sorted((p for p in source_dir.iterdir() if p.is_file()),
                       key=lambda p: p.name):
        if path.suffix.lower() not in _EXTENSIONS:
            continue
        imported.append(import_file(path, out_dir, slim=slim))
    if not imported:
        raise CanonicalImportError(source_dir, "no .md/.txt/.docx files found")
    return imported


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Import Markdown/docx/plain text into the canonical "
                    "content_list.json layout paper-metrics reads.")
    parser.add_argument("--source", required=True,
                        help="source file, or a directory of source files")
    parser.add_argument("--out", required=True, help="output corpus directory")
    parser.add_argument("--format", choices=["markdown", "docx", "text"], default=None,
                        help="force a format; otherwise inferred from the extension")
    parser.add_argument("--id", default=None, help="paper id (defaults to file stem)")
    parser.add_argument("--slim", action="store_true",
                        help="drop image blocks (fixture mode; S-SIZ-04 reads nothing)")
    args = parser.parse_args(argv)

    source = Path(args.source)
    out_dir = Path(args.out)
    try:
        if source.is_dir():
            paths = import_corpus(source, out_dir, slim=args.slim)
        else:
            paths = [import_file(source, out_dir, paper_id=args.id,
                                 source_format=args.format, slim=args.slim)]
    except CanonicalImportError as exc:
        print("[canonical_import] ERROR: " + str(exc), file=sys.stderr)
        return 2
    for path in paths:
        print("[canonical_import] " + str(source) + " -> " + str(path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
